# Generated by Django 4.0.1 on 2022-01-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='public',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
