# Generated by Django 4.0.1 on 2022-01-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_alter_bookmark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
    ]
